### ISSUE TITLE
ClassCastException TBClimateSampler

### ISSUE THREAD

**Issue by Yucked** [Glitchfiend/TerraBlender#18]
### What's the issue you encountered?

Throws an exception when initializing minecraft server, seems to be related to world generation according to exception stack trace.

```java
java.lang.ClassCastException: class net.minecraft.class_5818 cannot be cast to class terrablender.worldgen.TBClimate$Sampler (net.minecraft.class_5818 and terrablender.worldgen.TBClimate$Sampler are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @46d56d67)
        at terrablender.worldgen.TBMultiNoiseBiomeSource.method_38109(TBMultiNoiseBiomeSource.java:94) ~[TerraBlender-fabric-1.18.1-1.1.0.65.jar:?]
        at net.minecraft.class_1966.method_24385(class_1966.java:227) ~[server-intermediary.jar:?]
        at net.minecraft.class_1966.method_8762(class_1966.java:191) ~[server-intermediary.jar:?]
        at net.minecraft.class_2794.method_28509(class_2794.java:133) ~[server-intermediary.jar:?]
        at net.minecraft.class_2794.invokeGenerateStrongholdPositions(class_2794.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3754.handler$zod005$onInit(class_3754.java:3088) ~[server-intermediary.jar:?]
        at net.minecraft.class_3754.<init>(class_3754.java:124) ~[server-intermediary.jar:?]
        at net.minecraft.class_3754.<init>(class_3754.java:84) ~[server-intermediary.jar:?]
        at terrablender.worldgen.TBNoiseBasedChunkGenerator.<init>(TBNoiseBasedChunkGenerator.java:68) ~[TerraBlender-fabric-1.18.1-1.1.0.65.jar:?]
        at terrablender.worldgen.TBNoiseBasedChunkGenerator.<init>(TBNoiseBasedChunkGenerator.java:63) ~[TerraBlender-fabric-1.18.1-1.1.0.65.jar:?]
        at terrablender.api.WorldPresetUtils.chunkGenerator(WorldPresetUtils.java:110) ~[TerraBlender-fabric-1.18.1-1.1.0.65.jar:?]
        at terrablender.api.WorldPresetUtils.overworldChunkGenerator(WorldPresetUtils.java:48) ~[TerraBlender-fabric-1.18.1-1.1.0.65.jar:?]
        at net.minecraft.class_5285.handler$dab000$onCreate(class_5285.java:567) ~[server-intermediary.jar:?]
        at net.minecraft.class_5285.method_28021(class_5285.java:232) ~[server-intermediary.jar:?]
        at net.minecraft.class_3806.method_37371(class_3806.java:92) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:173) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
```

### How can the issue be reproduced?

Use any version of C2ME 1.18.1 with latest version of BYG and terrablender.

### Mod Version

1.1.0.65

**Comment by Adubbz** [comment]
This is probably related to the mixins they do which cause an unexpected state for TerraBlender. Probably worth reporting this to C2ME since I really don't know what they do.

**Comment by Yucked** [comment]
Yeah that's what I was thinking too. Thank you!
