### ISSUE TITLE
Crash updating from 1.1.0.73 to 1.1.0.77

### ISSUE THREAD

**Issue by evhub** [Glitchfiend/TerraBlender#52]
### What's the issue you encountered?

When updating the server from 1.1.0.73 to 1.1.0.77, the following crash is generated immediately after startup:
```
[16:58:24] [Server thread/FATAL]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkMap.m_199380_(ChunkMap.java:565) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:530) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:538) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:269) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:473) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:315) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:175) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:644) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 10
	at terrablender.worldgen.TBClimate$UniquenessRTree.search(TBClimate.java:178) ~[TerraBlender-forge-1.18.1-1.1.0.77.jar%23446!/:1.18.1-1.1.0.77]
	at terrablender.worldgen.TBClimate$ParameterList.findValueIndex(TBClimate.java:97) ~[TerraBlender-forge-1.18.1-1.1.0.77.jar%23446!/:1.18.1-1.1.0.77]
	at terrablender.worldgen.TBClimate$ParameterList.findValueIndex(TBClimate.java:93) ~[TerraBlender-forge-1.18.1-1.1.0.77.jar%23446!/:1.18.1-1.1.0.77]
	at terrablender.worldgen.TBClimate$ParameterList.findValue(TBClimate.java:89) ~[TerraBlender-forge-1.18.1-1.1.0.77.jar%23446!/:1.18.1-1.1.0.77]
	at terrablender.worldgen.TBMultiNoiseBiomeSource.getNoiseBiome(TBMultiNoiseBiomeSource.java:110) ~[TerraBlender-forge-1.18.1-1.1.0.77.jar%23446!/:1.18.1-1.1.0.77]
	at terrablender.worldgen.TBMultiNoiseBiomeSource.m_183546_(TBMultiNoiseBiomeSource.java:94) ~[TerraBlender-forge-1.18.1-1.1.0.77.jar%23446!/:1.18.1-1.1.0.77]
	at com.teamabnormals.blueprint.core.util.BiomeUtil$OriginalModdedBiomeProvider.getNoiseBiome(BiomeUtil.java:233) ~[blueprint-1.18.1-5.1.1.jar%23111!/:5.1.1]
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSource$WeightedBiomeSlices.getNoiseBiome(ModdedBiomeSource.java:177) ~[blueprint-1.18.1-5.1.1.jar%23111!/:5.1.1]
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSource.m_183546_(ModdedBiomeSource.java:99) ~[blueprint-1.18.1-5.1.1.jar%23111!/:5.1.1]
	at com.teamabnormals.blueprint.core.util.BiomeUtil$OriginalModdedBiomeProvider.getNoiseBiome(BiomeUtil.java:233) ~[blueprint-1.18.1-5.1.1.jar%23111!/:5.1.1]
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSource$WeightedBiomeSlices.getNoiseBiome(ModdedBiomeSource.java:177) ~[blueprint-1.18.1-5.1.1.jar%23111!/:5.1.1]
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSource.m_183546_(ModdedBiomeSource.java:99) ~[blueprint-1.18.1-5.1.1.jar%23111!/:5.1.1]
	at com.teamabnormals.blueprint.core.util.BiomeUtil$OriginalModdedBiomeProvider.getNoiseBiome(BiomeUtil.java:233) ~[blueprint-1.18.1-5.1.1.jar%23111!/:5.1.1]
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSource$WeightedBiomeSlices.getNoiseBiome(ModdedBiomeSource.java:177) ~[blueprint-1.18.1-5.1.1.jar%23111!/:5.1.1]
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSource.m_183546_(ModdedBiomeSource.java:99) ~[blueprint-1.18.1-5.1.1.jar%23111!/:5.1.1]
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_188684_(NoiseBasedChunkGenerator.java:239) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.world.level.chunk.ChunkAccess.m_187655_(ChunkAccess.java:358) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_183516_(NoiseBasedChunkGenerator.java:238) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187818_(ChunkStatus.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_183270_(ChunkStatus.java:313) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$20(ChunkMap.java:552) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2329!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:550) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:58) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.18.1-20211210.034407-srg.jar%23514!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

### How can the issue be reproduced?

Update from 1.1.0.73 to 1.1.0.77; likely only occurs when combined with abnormals mods as in the stack trace.

### Logs

https://gist.githubusercontent.com/evhub/146a80d314e0b3d24e88d78cf33b17db/raw/fe17ab842e38643e3cdcdfc9a43495175496074c/latest.log

### Mod Version

1.1.0.77

### Additional information

Forge version: 39.1.2

**Comment by Adubbz** [comment]
This has been addressed in 1.18.2.
