### ISSUE TITLE
[1.18.2] Mod crashes in server environment

### ISSUE THREAD

**Issue by Jissee** [Glitchfiend/TerraBlender#55]
### What's the issue you encountered?

The latest mod for Minecraft 1.18.2 works well in my client. However, it crashed when I tried to start my forge (40.0.12) server with TerraBlender (the only one) mod.

### How can the issue be reproduced?

1. Go to minecraftforge.net and download and install the server.
2. Start the server without TerraBlender and everything works well.
3. Add TerraBlender to the mods directory, and start the server again.
4. The server crashes while loading the mod. There is no crash-report but the console shows the reasons.

### Logs

2022-03-18 13:57:49,343 main WARN Advanced terminal features are not available in this environment
[13:57:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.0.12, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220228.144236]
[13:57:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Oracle Corporation
[13:57:49] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/Minecraft/svar1.18.2/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
[13:57:51] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[13:57:51] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[13:57:59] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 40.0.12, for MC 1.18.2 with MCP 20220228.144236
[13:57:59] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v40.0.12 Initialized
[13:58:00] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[13:58:02] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: BETA_OUTDATED Current: 40.0.12 Target: 40.0.19
[13:58:02] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:58:03] [main/WARN] [minecraft/VanillaPackResources]: Assets URL 'union:/D:/Minecraft/svar1.18.2/libraries/net/minecraft/server/1.18.2-20220228.144236/server-1.18.2-20220228.144236-srg.jar%2340!/assets/.mcassetsroot' uses unexpected schema
[13:58:03] [main/WARN] [minecraft/VanillaPackResources]: Assets URL 'union:/D:/Minecraft/svar1.18.2/libraries/net/minecraft/server/1.18.2-20220228.144236/server-1.18.2-20220228.144236-srg.jar%2340!/data/.mcassetsroot' uses unexpected schema
[13:58:06] [main/INFO] [terrablender/]: Registered region minecraft:overworld to index 0 for type OVERWORLD
[13:58:06] [main/INFO] [terrablender/]: Registered region minecraft:nether to index 0 for type NETHER
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.0.12/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
        at TRANSFORMER/terrablender@1.18.2-1.1.0.91/terrablender.util.RegistryUtils.<clinit>(RegistryUtils.java:31)
        at TRANSFORMER/terrablender@1.18.2-1.1.0.91/terrablender.worldgen.noise.InitialLayer.lambda$new$1(InitialLayer.java:43)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at TRANSFORMER/terrablender@1.18.2-1.1.0.91/terrablender.worldgen.noise.InitialLayer.<init>(InitialLayer.java:49)
        at TRANSFORMER/terrablender@1.18.2-1.1.0.91/terrablender.worldgen.noise.LayeredNoiseUtil.uniqueness(LayeredNoiseUtil.java:35)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.biome.Climate$ParameterList.initializeForTerraBlender(Climate.java:558)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.handler$zzc000$onInit(NoiseBasedChunkGenerator.java:634)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.<init>(NoiseBasedChunkGenerator.java:77)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.dimension.DimensionType.m_204493_(DimensionType.java:233)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.dimension.DimensionType.m_204490_(DimensionType.java:221)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.WorldGenSettings.m_209716_(WorldGenSettings.java:196)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServerProperties.m_180927_(DedicatedServerProperties.java:103)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.m_206537_(Main.java:176)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.WorldStem.m_206911_(WorldStem.java:40)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.main(Main.java:158)
        ... 13 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 35 more

### Mod Version

TerraBlender-forge-1.18.2-1.1.0.91.jar

**Comment by Adubbz** [comment]
You need to update the mod.
