### ISSUE TITLE
Doesn't work no matter the version for 1.18.2 fabric

### ISSUE THREAD

**Issue by Spirit72** [Glitchfiend/TerraBlender#92]
### What's the issue you encountered?

So i was trying to join my friend's minecraft server, he gave me a list of mods and extensivly tested them so we wouldn't have problems

I tried loading the mods up with fabric 1.18.2 and minecraft crashed after i clicked the button to play, it didn't even show me a screen or anything, it just refused to open

I tried again with only fabric api and terrablender but the problem is still there so i am unsure if my minecraft is broken or if i'm downloading the wrong fabric api

### How can the issue be reproduced?

Uhhhh download minecraft fabric for 1.18.2, download the most recent instance of fabric api for 1.18.2 with the same version for terrablender, and then try opening your game? thats literally all i did so i don't have much of a clue why it's happening, sorry :,)

### Logs

---- Minecraft Crash Report ---- // Uh... Did I do that?  Time: 2022-10-08, 6:11 p.m. Description: Initializing game  java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'terrablender'! 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) 	at net.minecraft.class_310.<init>(class_310.java:452) 	at net.minecraft.client.main.Main.main(Main.java:197) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.ExceptionInInitializerError 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:467) 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) 	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) 	... 7 more Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available 	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) 	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) 	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) 	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) 	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) 	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) 	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) 	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) 	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) 	at terrablender.config.ConfigFile.<init>(ConfigFile.java:34) 	at terrablender.config.TerraBlenderConfig.<init>(TerraBlenderConfig.java:31) 	at terrablender.core.TerraBlenderFabric.<clinit>(TerraBlenderFabric.java:37) 	... 13 more   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) 	at net.minecraft.class_310.<init>(class_310.java:452)  -- Initialization -- Details: 	Modules:  		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		AMSIExt.dll:McAfee Cloud AV ThirdParty Ext:25.2.133 b9d2d9ba diaphanous peacock:McAfee, LLC 		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation 		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation 		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		GDI32.dll:GDI Client DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation 		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation 		MpOav.dll:IOfficeAntiVirus Module:4.18.2207.7 (WinBuild.160101.0800):Microsoft Corporation 		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation 		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation 		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation 		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation 		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		SHELL32.dll:Windows Shell Common Dll:10.0.19041.964 (WinBuild.160101.0800):Microsoft Corporation 		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation 		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		WINHTTP.dll:Windows HTTP Services:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation 		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		amsi.dll:Anti-Malware Scan Interface:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation 		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation 		combase.dll:Microsoft COM for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation 		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.1503 (WinBuild.160101.0800):Microsoft Corporation 		gdi32full.dll:GDI Client DLL:10.0.19041.2006 (WinBuild.160101.0800):Microsoft Corporation 		java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		javaw.exe:OpenJDK Platform binary:17.0.1.0:Microsoft 		jemalloc.dll 		jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		jna9085363605447961290.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA) 		jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft 		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		lwjgl.dll 		management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		msvcp140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation 		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation 		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		ntdll.dll:NT Layer DLL:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation 		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation 		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation 		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation 		verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		win32u.dll:Win32u:10.0.19041.2006 (WinBuild.160101.0800):Microsoft Corporation 		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft Stacktrace: 	at net.minecraft.client.main.Main.main(Main.java:197) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)  -- System Details -- Details: 	Minecraft Version: 1.18.2 	Minecraft Version ID: 1.18.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.1, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 570872696 bytes (544 MiB) / 1912602624 bytes (1824 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 8 	Processor Vendor: GenuineIntel 	Processor Name: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz 	Identifier: Intel64 Family 6 Model 140 Stepping 1 	Microarchitecture: unknown 	Frequency (GHz): 3.30 	Number of physical packages: 1 	Number of physical CPUs: 4 	Number of logical CPUs: 8 	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics 	Graphics card #0 vendor: Intel Corporation (0x8086) 	Graphics card #0 VRAM (MB): 1024.00 	Graphics card #0 deviceId: 0x9a49 	Graphics card #0 versionInfo: DriverVersion=30.0.101.1631 	Graphics card #1 name: NVIDIA GeForce RTX 3060 Laptop GPU 	Graphics card #1 vendor: NVIDIA (0x10de) 	Graphics card #1 VRAM (MB): 4095.00 	Graphics card #1 deviceId: 0x2520 	Graphics card #1 versionInfo: DriverVersion=30.0.15.1278 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 20413.58 	Virtual memory used (MB): 14650.99 	Swap memory total (MB): 4352.00 	Swap memory used (MB): 245.24 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Fabric Mods:  		fabric-api: Fabric API 0.59.0+1.18.2 			fabric-api-base: Fabric API Base 0.4.4+d7c144a860 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560 			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560 			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860 			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60 			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860 			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860 			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860 			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360 			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60 			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60 			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860 			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60 			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60 			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260 			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560 			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60 			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560 			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860 			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560 			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960 		fabricloader: Fabric Loader 0.14.9 		java: OpenJDK 64-Bit Server VM 17 		minecraft: Minecraft 1.18.2 		terrablender: TerraBlender 1.2.0.126 			com_electronwill_night-config_core: core 3.6.4 			com_electronwill_night-config_toml: toml 3.6.4 	Launched Version: fabric-loader-0.14.9-1.18.2 	Backend library: LWJGL version 3.2.2 build 10 	Backend API: Unknown 	Window size: <not initialized> 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages: <disabled> 	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'fabric' 	Type: Client (map_client.txt) 	CPU: <unknown>

### Mod Version

none of the version for 1.18.2 will work but this is the one i want - TerraBlender-fabric-1.18.2-1.2.0.126.jar

### Additional information

Thank you for your help!

**Comment by Spirit72** [comment]
nvm turns out the config files needed to be murdered

Sorry for bothering you- have a nice day!
